version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: liveticker_eintracht_db
    environment:
      POSTGRES_USER: liveticker_user
      POSTGRES_PASSWORD: dev_password_123
      POSTGRES_DB: liveticker_eintracht
    ports:
      - "5434:5432"
    volumes:
      - postgres_eintracht_data:/var/lib/postgresql/data

volumes:
  postgres_eintracht_data:
